In [6]:
import pandas as pd

pd.DataFrame({'Yes': [1, 'Yes', 1], 'No': [0, 'No', 0]})

   Yes  No
0    1   0
1  Yes  No
2    1   0

In [5]:
import pandas as pd

pd.DataFrame({'Bob': ['I liked it.', 'It was awful.'], 
              'Sue': ['Pretty good.', 'Bland.'],
              'Jim': ['Great!', 'So bad.']},
              index=['Product A', 'Product B'])

                     Bob           Sue      Jim
Product A    I liked it.  Pretty good.   Great!
Product B  It was awful.        Bland.  So bad.

In [14]:
import pandas as pd

pd.Series([30, 35, 40], index=['2015 Sales', '2016 Sales', '2017 Sales'], 
          name='Product A')

2015 Sales    30
2016 Sales    35
2017 Sales    40
Name: Product A, dtype: int64